# Generated by Django 4.2.7 on 2023-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.CharField(max_length=10),
        ),
    ]
