# Generated by Django 4.2.7 on 2023-11-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dono', models.CharField(max_length=50, verbose_name='Nome do Dono')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('telefone', models.CharField(max_length=10, verbose_name='Telefone')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tamanho', models.IntegerField(choices=[(0, 'Pequeno'), (1, 'Medio'), (2, 'Grande')], verbose_name='Tamanho')),
                ('turno', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde')], max_length=10, verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Reserva de Banho',
                'verbose_name_plural': 'Reservas de Banhos',
            },
        ),
    ]
